[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && gunicorn app:app --config gunicorn_config.py --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
name = "web"
type = "web"